services:
  
  backend:
    build: ./backend
    container_name: arkanoid-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=arkanoid
      - DB_PASSWORD=arkanoid_pass
      - DB_NAME=arkanoid
      - CENTRIFUGO_API_URL=http://centrifugo:8000/api
      - CENTRIFUGO_API_KEY=your_secret_api_key_here
      - CENTRIFUGO_WS_URL=ws://localhost:8000/connection/websocket   # для клиентов
    depends_on:
      postgres:
        condition: service_healthy
      centrifugo:
        condition: service_started
    volumes:
      - ./backend:/app
      - /app/vendor   # чтобы не пересобирать зависимости каждый раз


  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    command: centrifugo -c config.json
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    ports:
      - "8001:8000"

networks:
  dzenntask_rabbit:
    external: true

volumes:
  caddy_data:
  caddy_config:
  database_data:

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###

###< doctrine/doctrine-bundle ###
